language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DV=1.8.18
  - DV=1.9.13
  - DV=1.10.8
  - DV=1.11.7
install:
  - pip install Django==$DV
  - pip install -e .
script:
  - ./run_tests.sh
notifications:
  email:
    - jose@linux.com
