language: python
python:
  - "2.6"
  - "2.7"
env:
  - DV=1.3.7
  - DV=1.4.5
  - DV=1.5.1
install:
  - pip install Django==$DV
  - pip install -e .
script:
  - ./run_tests.sh
notifications:
  email:
    - ci@callowayproject.com